### ISSUE TITLE
Warzone API

### ISSUE THREAD

**Issue by iLazlow** [EthanC/CallofDuty.py#18]
Its not really a feature request.
There exists an endpoint for warzone matches, they being tracked separated:
 https://my.callofduty.com/api/papi-client/crm/cod/v2/title/mw/platform/{PLATFORM}/gamer/{USERNAME}/matches/wz/start/0/end/0/details

**Comment by felipemoran** [comment]
Do you know if there's any documentation (official or not) on this API for warzone?

My specific use case is getting info on a specific match a squad played (such as kills per player and ranking position) without loading a ton of other matches as I would with the endpoint you suggested

**Comment by iLazlow** [comment]
It seems there is an API for single Matches unfortunately i havent found it yet.

**Comment by tyeoneill** [comment]
Is it just a case of brute force? How do people find these? 

One thing that’s annoying about the above endpoint is that the platform and usernames don’t always agree. It’ll say psn but the name will be an Activision account.

**Comment by iLazlow** [comment]
Some endpoints are hidden and can be found if you sniff the network between the call of duty app on a mobile device, but not all endpoints are called via App. cod.tracker.gg seems to have exclusive access to an documented api. They explained somewhere on twitter, they have email contact with activision. Maybe you can ask them and they will eventually give you the endpoint. Idk

**Comment by EthanC** [comment]
I've added Warzone to the Modes Enum in 1.2.1.

> Do you know if there's any documentation (official or not) on this API for warzone?
@felipemoran There is no documentation for the Call of Duty API, public or private.

> Is it just a case of brute force? How do people find these?
@felipemoran As @iLazlow mentioned, the endpoints are found by sniffing the network traffic of the official Companion App, as well as the My Call of Duty website.

> One thing that’s annoying about the above endpoint is that the platform and usernames don’t always agree. It’ll say psn but the name will be an Activision account.
@felipemoran For Warzone matches, the `platform` value will designate which platform the player was playing on; However, the `username` value will always display their Activision ID, without the discriminator (where applicable.)

> cod.tracker.gg seems to have exclusive access to an documented api.
@iLazlow I work for COD Tracker, we don't have any sort of documentation for the Call of Duty API at this time.
