### ISSUE TITLE
Readme Code doesn't work?

### ISSUE THREAD

**Issue by zbhayat0** [EthanC/CallofDuty.py#34]
Hey,

I used the readme code - added my login username and password. Then I replaced the "Captain Price" with my own Activision ID (ZB3#3180831) but I get this error. 

Traceback (most recent call last):
  File "/Users/zafarb/PycharmProjects/TrackerAPI/API.py", line 27, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/Users/zafarb/PycharmProjects/TrackerAPI/API.py", line 15, in main
    me = results[1]
IndexError: list index out of range
ZB3#3180831 (Activision)

Process finished with exit code 1

**Comment by zbhayat0** [comment]
If I take out the "asyncio.get_event_loop().run_until_complete(main())" 
nothing happens and the process finishes with an exit code of 0 but nothing else happens

**Comment by tyeoneill** [comment]
If you’ve searched your unique name then there’s only one result. result[1] asks for the second result, try result[0].

**Comment by zbhayat0** [comment]
Appreciate it, and sorry I missed that lol - now I am just trying to figure out if there is a way for me to pull the API from the most recent matches I have played.

**Comment by shahbazk8194** [comment]
On a related note, I'm seeing:
`AttributeError: 'Client' object has no attribute 'Logout'`
when I'm trying to log out of the client via: `await client.Logout()`

I don't see the Logout function defined anywhere. Thoughts?

**Comment by EthanC** [comment]
The `Logout` function is depreciated as it really wasn't necessary, I'll update the README. Thanks!
