### ISSUE TITLE
Match History Limit

### ISSUE THREAD

**Issue by tyeoneill** [EthanC/CallofDuty.py#35]
### Summary

Match history only seems to return last 20 results, yet cod.tracker.gg is able to pull everything? 

I've tried looking at the url manually and the result is the same. So how does tracker network manage this? 

https://www.callofduty.com/api/papi-client/crm/cod/v2/title/mw/platform/uno/gamer/hazzeh/matches/mp/start/0/end/0/details

Setting the `startTimestamp` and `endTimestamp` in milliseconds seems to do be the only way to get older matches. Is there a more efficient way of getting them all? 

### Reproduction Steps

    async def main():
        load_dotenv()
        client = await callofduty.Login("nunya@business.com","password")

        player = await client.GetPlayer(Platform.Activision, "Hazzeh")
        matches = (await player.matches(Title.ModernWarfare, Mode.Multiplayer, limit=100))
        for match in matches:
            print(match.id)

    asyncio.get_event_loop().run_until_complete(main())

### Expected Results

A list of 100 matches, or as many matches as has been played by the player.

### Actual Results

A list of just 20 matches.

### Checklist

-   [x] I have searched the open Issues for duplicates
-   [x] I have shown the entire traceback, if possible
-   [x] I have removed my token from display, if visible

**Comment by EthanC** [comment]
The Activision platform requires a different endpoint to be used when gathering Matches, which doesn't support more a `limit` of more than `20`. If you lookup the first party identity (BattleNet, Xbox, PlayStation) for this account, you should get the desired results.

COD Tracker is storing the Match data, not just serving it directly from the Call of Duty API.
