### ISSUE TITLE
Trying to retrieve match details gives "200 - The specified key does not exist."

### ISSUE THREAD

**Issue by amackenzie** [EthanC/CallofDuty.py#39]
### Summary

When trying to retrieve match details, either via client.GetPlayerMatches and then trying to get results[0].details(), or directly via client.GetMatchDetails with a specified match ID, the function fails with an "HTTP 200 - The specified key does not exist" error.

I wanted to check to make sure I'm using this right, or if there's some nuance I'm missing as well.

### Reproduction Steps

After setting up the login as presented on the main page, I did:

```
    matches = await client.GetPlayerMatches(platform=Platform.BattleNet, username="stermy#2796", title=Title.ModernWarfare, mode=Mode.Warzone)
    pprint.pprint(await matches[0].details())
```

which successfully gets a list of matches but fails to get the details for any of the matches,

or

```
    match = await client.GetMatchDetails(title=Title.ModernWarfare, platform=Platform.BattleNet, matchId=14719957774703801961)
    pprint.pprint(match)
```

which fails to get the details for any of the matches.

### Expected Results

I expected to be able to find data relating to the match from calling either .details() or from using GetMatchDetails.

### Actual Results

```
Traceback (most recent call last):
  File ".\cod_api_test.py", line 39, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "c:\users\<username removed>\scoop\apps\python\3.8.3\lib\asyncio\base_events.py", line 616, in run_until_complete
    return future.result()
  File ".\cod_api_test.py", line 34, in main
    pprint.pprint(await matches[0].details())
  File "C:\Users\<username removed>\.virtualenvs\warzone20200618_stats-pkWWEdsn\lib\site-packages\callofduty\match.py", line 58, in details
    return await self._client.GetMatchDetails(self.title, self.platform, self.id)
  File "C:\Users\<username removed>\.virtualenvs\warzone20200618_stats-pkWWEdsn\lib\site-packages\callofduty\client.py", line 799, in GetMatchDetails
    return (await self.http.GetMatch(title.value, platform.value, matchId))["data"]
  File "C:\Users\<username removed>\.virtualenvs\warzone20200618_stats-pkWWEdsn\lib\site-packages\callofduty\http.py", line 263, in GetMatch
    return await self.Send(
  File "C:\Users\<username removed>\.virtualenvs\warzone20200618_stats-pkWWEdsn\lib\site-packages\callofduty\http.py", line 113, in Send
    raise HTTPException(res.status_code, data)
callofduty.errors.HTTPException: HTTP 200 - The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 6C8C445C3C151A37; S3 Extended Request ID: dsJ8YDIwQ10wDJD9srbyYHKEnk78MzK5txEJCf/ZwXQrEB0GcdcbUHgd0hXyMefq5E1fbSmNd60=)
```

### Checklist

-   [x] I have searched the open Issues for duplicates
-   [x] I have shown the entire traceback, if possible
-   [x] I have removed my token from display, if visible

### System Information

```
No module named callofduty.__main__; 'callofduty' is a package and cannot be directly executed
```

pip show callofduty.py gives:

```
Name: callofduty.py
Version: 1.2.1
Summary: CallofDuty.py is an asynchronous, object-oriented Python wrapper for the Call of Duty API.
Home-page: https://github.com/EthanC/CallofDuty.py
Author: EthanC
Author-email: EthanC@github.com
License: MIT
Location: (path removed due to presence of some usernames and stuff)
Requires: httpx
Required-by:
```

Python version 3.8.3, running on Windows 10.

**Comment by EthanC** [comment]
The Call of Duty API endpoint for match details does not support Warzone at the moment.

Throwing a unique exception for this isn't consistent with the design of the library, hence the presence of an HTTPException.

**Comment by ionelmc** [comment]
@EthanC isn't there a way to get match details for warzone? How does cod.tracker.gg do it? They appear to have almost all the details (just the rooster is missing but that isn't the most important thing).
