### ISSUE TITLE
Unable to pull down warzone match info

### ISSUE THREAD

**Issue by JacobTWright** [EthanC/CallofDuty.py#46]
### Summary

Attempting to pull down warzone matches results in the following error:

HTTP 200 - The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: B4ACCB323C5277CF; S3 Extended Request ID: /nxElXneStDr8MdgbBtxLJ+x12n54Hnpt463Qf/TYofGbSTmu8L56coRyhF2yRYUwZPLvCWEZGw=)

### Reproduction Steps

async def main():
    client = await callofduty.Login("MyEmail@email.com", "MyPassword")

    results = await client.SearchPlayers(Platform.BattleNet, "MyUser", limit=3)
    for player in results:
        print(f"{player.username} ({player.platform.name})")

    me = results[0]
    matches_list = me.matches(Title.ModernWarfare, Mode.Warzone)
    for match in matches_list:
        details = match.details()
    

### Expected Results

match.details to return an object containing match detials

### Actual Results

HTTPException                             Traceback (most recent call last)
<ipython-input-107-5d681ad9243b> in <module>
----> 1 res = await matches_list[0].details()

/mnt/c/Users/Jake/Documents/Python/CallofDuty.py/callofduty/match.py in details(self)
     56         """
     57
---> 58         return await self._client.GetMatchDetails(self.title, self.platform, self.id)

/mnt/c/Users/Jake/Documents/Python/CallofDuty.py/callofduty/client.py in GetMatchDetails(self, title, platform, matchId)
    797         VerifyTitle(title)
    798
--> 799         return (await self.http.GetMatch(title.value, platform.value, matchId))["data"]
    800
    801     async def GetMatchTeams(

/mnt/c/Users/Jake/Documents/Python/CallofDuty.py/callofduty/http.py in GetMatch(self, title, platform, matchId)
    264     ) -> Union[dict, list, str]:
    265         print(  f"api/papi-client/ce/v1/title/{title}/platform/{platform}/match/{matchId}/matchMapEvents")
--> 266         return await self.Send(
    267             Request(
    268                 "GET",

/mnt/c/Users/Jake/Documents/Python/CallofDuty.py/callofduty/http.py in Send(self, req)
    111                 # The API tends to return HTTP 200 even when an error occurs
    112                 if status == "error":
--> 113                     raise HTTPException(res.status_code, data)
    114
    115             # HTTP 2XX: Success

HTTPException: HTTP 200 - The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 241B52B18B0B084E; S3 Extended Request ID: pu5ky+2yntwdBJamck7onLQdpzdhbVUt44PTmdZvpuTNYyZ5Yy/ExLEPT6STGAdmuZ/WKZqkvJQ=)

### Checklist

-   [x ] I have searched the open Issues for duplicates
-   [x ] I have shown the entire traceback, if possible
-   [x ] I have removed my token from display, if visible

### System Information

python 3.8, callofduty version 1.2.1

**Comment by Jmegan042** [comment]
I have reproduced this problem and can verify that this pathway does not work. 

Additionally, I am having issues with the related function from client.GetMatchDetails - same error code. 

`import asyncio

import callofduty
from callofduty import Mode, Platform, Title


async def main():
    client = await callofduty.Login("USER_LOGIN", "USER_PASS")
    # client.GetMatchDetails(Title.ModernWarfare, Mode.Warzone)

    results = await client.SearchPlayers(Platform.Activision, "USERNAME_ID", limit=3)
    me = results[0]
    matches = await me.matches(Title.ModernWarfare, Mode.Warzone)
    match = matches[0].id
    Match_Results = await client.GetMatchDetails(Title.ModernWarfare,Platform.Activision,match)
    print(Match_Results)
    


asyncio.get_event_loop().run_until_complete(main())`

Produces: 

_.....line 113, in Send
    raise HTTPException(res.status_code, data)
callofduty.errors.HTTPException: HTTP 200 - The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 407401B08ED58735; S3 Extended Request ID: bBHzDn8NryfPbFlpvqTODzxJWYkAgn4ZL5GNr9HgRvk3NfvWIBf/n736eih9cBoj/2mR+86WPQo=)_

**Comment by EthanC** [comment]
This is fixed in the latest version (v1.2.2), see `GetFullMatch()`.
