### ISSUE TITLE
Issue with client.GetPlayerLoadouts

### ISSUE THREAD

**Issue by JayBabs** [EthanC/CallofDuty.py#47]
### Summary

I'm trying to play with this repo, I have look at the documentation but also loadout.py and client.py. I'm still a beginner with python, feel free to guide me. 

### Reproduction Steps

async def main():
    client = await callofduty.Login("#email", "#password")

loadouts = await client.GetPlayerLoadouts(Platform.Activision,"BeauBrun#4481907",Title.ModernWarfare)

### Expected Results

I'm expecting the list of loadouts 

### Actual Results

  File "/usr/local/lib/python3.8/site-packages/callofduty/client.py", line 1128, in GetPlayerLoadouts
    for _loadout in data["loadouts"]:

### Checklist

I left the Activision ID , this way you would be able to recreate the same test 

### System Information

Python3.8 and lastest version of Callofduty

**Comment by EthanC** [comment]
The title Modern Warfare does not support this endpoint currently, only Black Ops 4. This is a decision made by Activison, not this library.
