### ISSUE TITLE
Warzone data

### ISSUE THREAD

**Issue by andbucci** [EthanC/CallofDuty.py#48]
I am trying to extract the KD for a list of 80k players. I am not sure how to do that, could you please provide me an example?

For a single player, this is not working:

import asyncio

import callofduty
from callofduty import Mode, Platform, Title

async def main():
    client = await callofduty.Login("Mail", "Password")

    results = await client.SearchPlayers(Platform.Xbox, "Int183347", limit=3)
    for player in results:
        print(f"{player.username} ({player.platform.name})")

    me = results[0]
    profile = await me.profile(Title.ModernWarfare, Mode.Warzone)

    level = profile["level"]
    kd = profile["lifetime"]["all"]["properties"]["kdRatio"]

    print(f"\n{me.username} ({me.platform.name})")
    print(f"Level: {level}, K/D Ratio: {kd}")

    await client.Logout()

asyncio.get_event_loop().run_until_complete(main())

Furthermore, I have a list of 600 match ids from which I would like to extract the list of players. Now, this is pretty simple working with json. However, the problem is that I am not able to extract the platform these players are using. Is there a way to extract it from your docker?

**Comment by EthanC** [comment]
Unfortunately I cannot offer support like this, Issues are reserved for Feature Requests and Bugs.
