### ISSUE TITLE
Warzone matches

### ISSUE THREAD

**Issue by Ste29** [EthanC/CallofDuty.py#49]
### Summary

When you try to use the function getMatch on a warzone match the API doesn't work
### Reproduction Steps

```import callofduty
import asyncio
from callofduty import Mode, Platform, Title


async def main():
    client = await callofduty.Login("youremail@email.com", "psw")
  
    # match = await client.GetMatch(Title.ModernWarfare, Platform.Activision, 10001)
    # il WILLICO #7036849
    match = await client.GetPlayerMatches(Platform.Activision, "il WILLICO#7036849", Title.ModernWarfare, Mode.Warzone)
    prova1 = await match[1].teams()
    print(type(prova1))

#    await client.Logout()

asyncio.get_event_loop().run_until_complete(main())

```

### Expected Results

I'm expecting the details/teams about the match

### Actual Results

it gives an error because it doesn't find the match
`Traceback (most recent call last):
  File "C:\Users\Stefano\Desktop\cod_app\cod_stats.py", line 49, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "C:\Program Files\Python39\lib\asyncio\base_events.py", line 642, in run_until_complete
    return future.result()
  File "C:\Users\Stefano\Desktop\cod_app\cod_stats.py", line 40, in main
    prova1 = await match[1].teams()
  File "C:\Users\Stefano\Desktop\cod_app\lib\site-packages\callofduty\match.py", line 46, in teams
    return await self._client.GetMatchTeams(self.title, self.platform, self.id)
  File "C:\Users\Stefano\Desktop\cod_app\lib\site-packages\callofduty\client.py", line 827, in GetMatchTeams
    data: dict = (await self.http.GetMatch(title.value, platform.value, matchId))[
  File "C:\Users\Stefano\Desktop\cod_app\lib\site-packages\callofduty\http.py", line 263, in GetMatch
    return await self.Send(
  File "C:\Users\Stefano\Desktop\cod_app\lib\site-packages\callofduty\http.py", line 113, in Send
    raise HTTPException(res.status_code, data)
callofduty.errors.HTTPException: HTTP 200 - The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 238D84755E903789; S3 Extended Request ID: u7Sz2H48EHaElwLLiODYniNfkmwfz96ARewkcn59i99t3Eowvi234bmTqpyPN1IIi/XKWxEUJIc=)
`

The problem is inside http.py at line 266, indeed the get request doesn't work for warzone matches and it works only on multiplayer matches according to this link:
https://documenter.getpostman.com/view/5519582/SzzgAefq#f03a4eeb-58c3-4486-aea2-f59ed692a655
### Checklist

-   [x] I have searched the open Issues for duplicates
-   [x] I have shown the entire traceback, if possible
-   [x] I have removed my token from display, if visible

### System Information

python 3.9

**Comment by EthanC** [comment]
This is fixed in the latest version (v1.2.2), see `GetFullMatch()`.
