### ISSUE TITLE
Match Details request fails

### ISSUE THREAD

**Issue by mbeattie** [EthanC/CallofDuty.py#52]
### Summary

A request for Match Details fails on the API side

### Reproduction Steps

Log in, find my own profile, look at my matches, and get details

myself = await client.GetPlayer(Platform.Activision, "xxx#123")
matches = await myself.matches(Title.ModernWarfare, Mode.Warzone)
for match in matches:
    match_details = await match.details()
    
### Expected Results

I expect to see details of the match

### Actual Results

The API itself fails

  File "/home/me/warzone.py", line 30, in main
    match_details = await match.details()
  File "/home/me/venv/lib/python3.9/site-packages/callofduty/match.py", line 58, in details
    return await self._client.GetMatchDetails(self.title, self.platform, self.id)
  File "/home/me/venv/lib/python3.9/site-packages/callofduty/client.py", line 840, in GetMatchDetails
    return (await self.http.GetMatch(title.value, platform.value, matchId))["data"]
  File "/home/me/venv/lib/python3.9/site-packages/callofduty/http.py", line 263, in GetMatch
    return await self.Send(
  File "/home/me/venv/lib/python3.9/site-packages/callofduty/http.py", line 113, in Send
    raise HTTPException(res.status_code, data)
callofduty.errors.HTTPException: HTTP 200 - The specified key does not exist. (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: 12345; S3 Extended Request ID: abcdefg)

Looks like they are using some S3 bucket behind the API, but whatever the endpoint is doing is failing to look that up... not sure if this is because something changed in the API or the library needs to use a different endpoint or something. I don't see any documentation from Activision to try to decipher what request it should be making.

### Checklist

-   [x] I have searched the open Issues for duplicates
-   [x] I have shown the entire traceback, if possible
-   [x] I have removed my token from display, if visible

### System Information

python -m callofduty -v
/home/me/venv/bin/python: No module named callofduty.__main__; 'callofduty' is a package and cannot be directly executed

Python 3.9.0
callofduty.py==1.2.2

Fedora 33

**Comment by EthanC** [comment]
Use `GetFullMatch()` for Warzone matches, the Activision API doesn't support it otherwise.
