### ISSUE TITLE
Loadout URL Bad

### ISSUE THREAD

**Issue by TrynCatchMehh** [EthanC/CallofDuty.py#53]
The loadout URL that is provided was removed from COD servers weeks ago, Can we get that updated?

**Comment by PeterEstephan** [comment]
+1
 I would much appreciate it if this was updated and fixed!

**Comment by PeterEstephan** [comment]
When I do a GET request for: https://www.callofduty.com/api/papi-client/loadouts/:version/title/:game/platform/:platform/gamer/:username/mode/mp (mp or wz)
I am presented with the following message in return: 
`{
    "status": "error",
    "data": {
        "type": "java.lang.Exception",
        "message": "No loadout available for title with id: mw"
    }
}`

**Comment by EthanC** [comment]
This is simply a depreciation, there are no fixes for it that can be applied to this project.
