### ISSUE TITLE
Not working GetPlayerMatches for Warzone mode 

### ISSUE THREAD

**Issue by gianluca2414** [EthanC/CallofDuty.py#56]
### Summary

Function GetPlayerMatches not working if the mode is Mode.Warzone

### Checklist

-   [x] I have searched the open Issues for duplicates
-   [x] I have shown the entire traceback, if possible
-   [ ] I have removed my token from display, if visible

### Example of the code i tried

    myCodID = 'gianluca2414#5528619'

    client = await callofduty.Login("emailActivison", "PASSWORD")

    match = (await client.GetPlayerMatches(Platform.Activision, myCodID, Title.ModernWarfare, Mode.Warzone, limit=1))[0]
    teams = await match.teams()
    print(teams)

### Traceback

Traceback (most recent call last):
  File "Test.py", line 30, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "Test.py", line 20, in main
    match = (await client.GetPlayerMatches(Platform.Activision, "Yeah#8649242", Title.ModernWarfare, Mode.MultiPlayer, limit=3))[0]
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/enum.py", line 341, in __getattr__
    raise AttributeError(name) from None
AttributeError: MultiPlayer
GIALLU:python3 Test.py
[[<Player>, <Player>, <Player>, <Player>, <Player>]]
GIALLU:clear

GIALLU:python3 Test.py
Traceback (most recent call last):
  File "Test.py", line 30, in <module>
    asyncio.get_event_loop().run_until_complete(main())
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "Test.py", line 21, in main
    teams = await match.teams()
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/callofduty/match.py", line 46, in teams
    return await self._client.GetMatchTeams(self.title, self.platform, self.id)
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/callofduty/client.py", line 827, in GetMatchTeams
    data: dict = (await self.http.GetMatch(title.value, platform.value, matchId))[
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/callofduty/http.py", line 263, in GetMatch
    return await self.Send(
  File "/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/callofduty/http.py", line 127, in Send
    raise HTTPException(res.status_code, data)
callofduty.errors.HTTPException: HTTP 500 - ï»¿<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html>

<head>
    <meta http-equiv="content-type" content="text/html; charset=UTF-8"/>
    <meta http-equiv="keywords" content=""/>
    <meta http-equiv="description" content=""/>
	<meta property="og:title" content="Call of Duty&reg; - Unexpected Error" />
	<meta property="og:description" content=""/>
	<meta property="og:url" content="/error-404" />
	<meta property="og:site_name" content="" />
	<meta property="og:image" content="" />
	<link rel="image_src" href=""/>
	<meta name="apple-mobile-web-app-title" content="Call of Duty&reg; - Unexpected Error"/> 
	<meta name="viewport" content="width=device-width, minimum-scale=1.0, maximum-scale=1.0, user-scalable=no"/>	
    <link rel="icon" type="image/vnd.microsoft.icon" href="/cod/error/img/favicon.ico">
    <link rel="shortcut icon" type="image/vnd.microsoft.icon" href="/cod/error/img/favicon.ico">
	
	<link href="/cod/error/css/error-404.css" rel="stylesheet" type="text/css"/>
    <title>Call of Duty&reg; - Unexpected Error</title>
    <script src="//assets.adobedtm.com/386a89de09ad0d27406fc28432e1961e4a099d4c/satelliteLib-695194b1db0dbf3c812ec72d3f11a95f199cedc1.js"></script>
    
</head>

<body id="" class="cod-404">

 
    
    <div style="height: 40px">
    </div>

<div class="container clearfix">
    <div class="content">
		<div id="header-nav">
			<div id="hero-header">
				<div id="hero-header-c0">
					<div id="cod-logo"><img src="/cod/error/img/cod_logo.png" alt="Call of Duty&reg;" width="166" height="106" />
					</div>
				</div>
				<div id="hero-header-c1">
					<p><a href="http://shop.callofduty.com" title="" target="_blank" class="preorder-link">Store</a></p>
				</div>
			</div>
		</div>
		<div id="hero">
			<div id="featured-txt" class="clearfix">
				<h2>Sorry, an unexpected error occurred.</h2>
				<p>UNBEKANNTER FEHLER.</p>
				<p>SI Ã VERIFICATO UN ERRORE IMPREVISTO.</p>
				<p>LO SENTIMOS, SE HA PRODUCIDO UN ERROR INESPERADO.</p>
				<p>DÃSOLÃ, UNE ERREUR INATTENDUE EST SURVENUE.</p>
				<br>
				<p>Go back to the Call of Duty website:</p>
				<ul>
					<li><a title="Call of DutyÂ®" href="http://www.callofduty.com" class="button">Call of duty<sup>&reg;</sup></a></li>

                    <li><a title="Call of dutyÂ®: Modern Warfare" href="http://www.callofduty.com/modernwarfare" class="button">Call of duty<sup>&reg;</sup>: MODERN WARFARE</a></li>
					
                    <li><a title="Call of dutyÂ®: Black Ops IIII" href="http://www.callofduty.com/blackops4" class="button">Call of duty<sup>&reg;</sup>: BLACK OPS IIII</a></li>
					
                    <li><a title="Call of dutyÂ®: WWII" href="http://www.callofduty.com/wwii" class="button">Call of duty<sup>&reg;</sup>: WWII</a></li>
					

				</ul>
		    <p>If your problem persists, please contact Activision Support.</p>
				<ul>
					<li><a class="button" title="VISIT SUPPORT" href="http://support.activision.com">VISIT SUPPORT</a></li>
				</ul>
			</div>
		</div>

		<div id="connect" class="atvi-component atvi-floater " style="right: 0; width:50px; position:absolute;">
			<div class="connect-content">
				<ul id="connect-list" class="atvi-component atvi-list ">
					<li class="text-list-item list-0">
						<div class="text parbase connect-list-t0">
						<div id="" class="atvi-component atvi-text  clearfix">
							<p><a href="http://www.facebook.com/codblackops" rel="nofollow" target="_blank" class="connect-fb">Facebook</a></p>
						</div></div>
					</li>
					<li class="text-list-item list-1">
						<div class="text parbase connect-list-t1">
						<div id="" class="atvi-component atvi-text  clearfix">
							<p><a rel="nofollow" target="_blank" href="http://www.twitter.com/callofduty" class="connect-twitter">Twitter</a></p>
						</div></div>
					</li>
					<li class="text-list-item list-2">
						<div class="text parbase connect-list-t2">
						<div id="" class="atvi-component atvi-text  clearfix">
							<p><a rel="nofollow" target="_blank" href="http://youtube.com/callofduty" class="connect-yt">Youtube</a></p>
						</div></div>
					</li>
					<li class="text-list-item list-3">
						<div class="text parbase connect-list-t3">
						<div id="" class="atvi-component atvi-text  clearfix">
							<p><a rel="nofollow" target="_blank" href="https://plus.google.com/105442945478799470998?prsrc=3" class="connect-google">Google</a></p>
						</div></div>
					</li>
				</ul>
			</div>
		</div>

		
	</div>
</div>
<div id="footer-container">
	<div id="footer">
		<div id="footer-top" class="clearfix">
			<div id="footer-top-c0">
				<a target="_blank" href="http://www.activision.com/" id="atvi-logo-image-link">
					<img width="294" height="64" title="" src="/cod/error/img/cod-hub-atvi-logo.png" alt="" class="atvi-image-image">
				</a>
			</div>
			<div id="footer-top-c1">
				<div id="connect-footer" class="connect-footer">
					<p>
						<span>Connect with us</span>
						<a class="connect-fb" target="_blank" href="http://www.facebook.com/codblackops">Facebook</a>
						<a class="connect-tw" target="_blank" href="http://twitter.com/CallofDuty">Twitter</a>
						<a class="connect-yt" target="_blank" href="http://www.youtube.com/callofduty">YouTube</a>
						<a class="connect-gp" target="_blank" href="https://plus.google.com/105442945478799470998?prsrc=3">Google+</a>
					</p>
				</div>
			</div>
		</div>
		<div id="footer-bottom" class="clearfix">
			<div id="footer-bottom-c0">
				<p>
					<a rel="nofollow" target="_blank" href="http://www.activision.com/atvihub/legal.do">Legal</a>
					/
					<a rel="nofollow" target="_blank" href="http://www.activision.com/atvihub/termsandconditions.do?sub=terms">Terms of Service</a>
					/
					<a rel="nofollow" target="_blank" href="http://www.activision.com/atvihub/privacy.do?sub=privacy">Privacy Policy</a>
					/
					<a rel="nofollow" target="_blank" href="http://www.activision.com/codsupport">Support</a>
				</p>
				<p>&copy; 2004-2012 Activision Publishing, Inc. ACTIVISION, CALL OF DUTY, MODERN WARFARE, CALL OF DUTY MW3, CALL OF DUTY BLACK OPS and stylized roman numeral II are trademarks of Activision Publishing, Inc. All other trademarks and trade names are the properties of their respective owners.</p>
			</div>
			<div id="footer-bottom-c1">
				<div id="footer-ratings-logos-c0">
					<div id="esrb-privacy-certified-logo">
						<a target="_blank" href="http://www.activision.com/atvihub/privacy.do?sub=privacy" id="esrb-privacy-certified-logo-image-link">
							<img width="144" height="53" title="" src="/cod/error/img/cod-hub-esrb-privacy-logo.png" alt="" />
						</a>		
					</div>
				</div>
				<div id="footer-ratings-logos-c1">
					<div id="pegi-online-logo">
						<a target="_blank" href="http://www.pegionline.eu/" id="pegi-online-logo-image-link">
							<img width="58" height="74" title="" src="/cod/error/img/cod-hub-pegi-logo.png" alt="" />
						</a>
					</div>
				</div>
				<div id="footer-ratings-logos-c2">
					<div id="mature-rating-logo">
						<a target="_blank" href="http://www.esrb.org/ratings/ratings_guide.jsp" id="mature-rating-logo-image-link">
							<img width="154" height="72" title="" src="/cod/error/img/cod-hub-mature-rating.png" alt="" />
						</a>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>

<script>
var digitalData = {"page": {
  "pageInfo": {
    "charSet": "UTF-8",
    "language": "EN",
    "country": "US",
    "site": "callofduty",
    "referPageURL": window.location.href
    },
  "pageCategory": {
    "pageType": "errorPage"
    }
  }};
  </script>
<script type="text/javascript">_satellite.pageBottom();</script>

</body>

</html>

**Comment by sardylan** [comment]
Same error for me, returns status code 500.

**Comment by EthanC** [comment]
See `client.GetFullMatch()` in v1.2.2.
