### ISSUE TITLE
GetMatch returns HTTP 500 error, whereas GetFullMatch still works

### ISSUE THREAD

**Issue by kkmille** [EthanC/CallofDuty.py#61]
https://github.com/EthanC/CallofDuty.py/blob/4b9436aaddb480f7e3ed04d8ef2ceb7dc32d5361/callofduty/http.py#L260

It looks like the endpoint has been removed by Activition
`api/papi-client/ce/v1/title/{title}/platform/{platform}/match/{matchId}/matchMapEvents`

It might be interesting to use the `GetFullMatch` method rather than `GetMatch` in the `match.details()` method

**Comment by alecaserez** [comment]
This is also affecting 

`teams = await match.teams()`

impossible to get the team

**Comment by JayBabs** [comment]
You should dig in the fullMatch there's a lot of information, I could submit a example of code and the json if you want to

**Comment by alecaserez** [comment]
The code for example.

`   match = (await client.GetPlayerMatches(Platform.Activision, "Yeah#8649242", Title.ModernWarfare, Mode.Warzone, limit=3))[0]
    teams = await match.teams()
    print(teams)`

**Comment by JayBabs** [comment]
async def dernier_classement(nested_list,client):

    for profil in nested_list:

        #profil[0] = username
        
        #profil[2] = matchid

        if profil[0] == "Undead_Somnium":

            joueur = await client.GetPlayer(Platform.PlayStation, profil[0])

        else: 

             joueur = await client.GetPlayer(Platform.Activision, profil[0])

        match = (await joueur.matches(Title.ModernWarfare, Mode.Warzone, limit=1))[0]
        match = await client.GetFullMatch(Platform.Activision, Title.ModernWarfare, Mode.Warzone, match.id)

        for players in match['allPlayers']:

            nouveau_matchID = players['matchID']
            rank = players['playerStats']['teamPlacement']
            username = players['player']['username']
            teamCount = players['teamCount']
            mode_de_jeu = players['mode']

**Comment by EthanC** [comment]
The GetMatch function is not depreciated, it just does not accept Warzone matches due to a limitation of the Call of Duty API. GetFullMatch resolves this issue.
