### ISSUE TITLE
Add Friend Request, Removal, and Relationship Functionality

### ISSUE THREAD

**Issue by EthanC** [EthanC/CallofDuty.py#7]
- https://my.callofduty.com/api/papi-client/codfriends/v1/invite/uno/id/7427941?context=web
`{}`
- https://my.callofduty.com/api/papi-client/codfriends/v1/remove/uno/id/13940176918450289589?context=web
`{}`
- https://my.callofduty.com/api/papi-client/relationships/v1/friend/platform/uno/gamer/Dad%231869899/set/fav?context=web
`{"username":"Dad#1869899","platform":"uno","type":"fav"}`
- https://my.callofduty.com/api/papi-client/relationships/v1/friend/platform/uno/gamer/Dad%231869899/delete?context=web
`{}`

**Comment by TrynCatchMehh** [comment]
This just gives not authenticated error though any other API request on the account works fine.
